# Generated by Django 3.2.6 on 2021-09-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20210831_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='answer',
        ),
    ]
