# Generated by Django 3.2.6 on 2021-09-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0002_auto_20210831_1838'),
        ('comment', '0004_rename_question_comment_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_answer.answer'),
        ),
    ]
